# Generated by Django 2.2.12 on 2020-05-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='MachineLearningMethods',
            fields=[
                ('method_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
