# Generated by Django 2.2.11 on 2020-04-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlplatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineLearningMethods',
            fields=[
                ('method_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='id',
        ),
        migrations.AlterField(
            model_name='data',
            name='data_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
